# Generated by Django 3.1.2 on 2020-10-12 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_resizer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
